# Generated by Django 5.2 on 2025-06-24 06:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("MC_command", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="enchantment",
            name="max_level",
            field=models.PositiveIntegerField(
                default=127, help_text="附魔的最大等级, 例如 Sharpness 的最大等级是 127"
            ),
        ),
    ]
