# Generated by Django 5.2 on 2025-06-24 06:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("MC_command", "0002_enchantment_max_level"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appliedattribute",
            name="modifier_name",
            field=models.CharField(
                blank=True,
                help_text="[重要] 仅用于 1.20.4 及更早版本。1.20.5+ 版本已废弃此字段。",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="appliedattribute",
            name="operation",
            field=models.IntegerField(
                choices=[
                    (0, "add_value"),
                    (1, "add_multiplied_base"),
                    (2, "add_multiplied_total"),
                ],
                default=0,
            ),
        ),
    ]
