# Generated by Django 5.2 on 2025-06-24 08:02

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("MC_command", "0003_alter_appliedattribute_modifier_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="appliedattribute",
            name="uuid",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, help_text="修饰符的唯一ID，自动生成。"
            ),
        ),
    ]
