# Generated by Django 5.2 on 2025-06-25 01:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("MC_command", "0006_baseitem_item_type"),
    ]

    operations = [
        migrations.RenameField(
            model_name="enchantment",
            old_name="type",
            new_name="enchant_type",
        ),
    ]
