# Generated by Django 5.2 on 2025-06-25 12:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("MC_command", "0011_alter_appliedpotioneffect_options_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="baseitem",
            old_name="item_type",
            new_name="function_type",
        ),
        migrations.AlterField(
            model_name="appliedpotioneffect",
            name="is_ambient",
            field=models.BooleanField(default=False, help_text="设为True时粒子效果会有信标?"),
        ),
    ]
