# Generated by Django 5.2 on 2025-06-25 12:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("MC_command", "0012_rename_item_type_baseitem_function_type_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ItemType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="物品的基础类型名, 例如 'Sword'", max_length=50, unique=True
                    ),
                ),
            ],
            options={
                "verbose_name": "物品类型",
                "verbose_name_plural": "物品类型",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Material",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="材质的名称, 例如 'Diamond'", max_length=50, unique=True
                    ),
                ),
            ],
            options={
                "verbose_name": "材质",
                "verbose_name_plural": "材质",
                "ordering": ["name"],
            },
        ),
        migrations.AlterModelOptions(
            name="baseitem",
            options={
                "ordering": ["material__name", "item_type__name", "name"],
                "verbose_name": "基础物品",
                "verbose_name_plural": "基础物品",
            },
        ),
        migrations.AlterField(
            model_name="baseitem",
            name="function_type",
            field=models.CharField(
                choices=[
                    ("all", "普通物品"),
                    ("spawn_egg", "生成蛋"),
                    ("potion", "药水(箭/食物)"),
                    ("written_book", "成书"),
                    ("firework", "烟花火箭"),
                ],
                default="all",
                help_text="物品的功能分类",
                max_length=50,
                verbose_name="功能类型",
            ),
        ),
        migrations.AddField(
            model_name="baseitem",
            name="item_type",
            field=models.ForeignKey(
                blank=True,
                help_text="物品的基础类型 (例如: Sword)",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="MC_command.itemtype",
            ),
        ),
        migrations.AddField(
            model_name="baseitem",
            name="material",
            field=models.ForeignKey(
                blank=True,
                help_text="物品的材质 (例如: Diamond)",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="MC_command.material",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="baseitem",
            unique_together={("material", "item_type")},
        ),
    ]
