# Generated by Django 5.2 on 2025-06-25 12:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("MC_command", "0014_itemtype_item_type_id_material_material_id_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="baseitem",
            options={
                "ordering": ["name"],
                "verbose_name": "基础物品",
                "verbose_name_plural": "基础物品",
            },
        ),
        migrations.AlterModelOptions(
            name="itemtype",
            options={
                "ordering": ["display_name"],
                "verbose_name": "物品类型",
                "verbose_name_plural": "物品类型",
            },
        ),
        migrations.AlterModelOptions(
            name="material",
            options={
                "ordering": ["display_name"],
                "verbose_name": "材质",
                "verbose_name_plural": "材质",
            },
        ),
        migrations.RemoveField(
            model_name="itemtype",
            name="item_type_id",
        ),
        migrations.RemoveField(
            model_name="itemtype",
            name="name",
        ),
        migrations.RemoveField(
            model_name="material",
            name="material_id",
        ),
        migrations.RemoveField(
            model_name="material",
            name="name",
        ),
        migrations.AddField(
            model_name="itemtype",
            name="display_name",
            field=models.CharField(
                blank=True, help_text="用于显示的名称, e.g., '剑'", max_length=50, null=True
            ),
        ),
        migrations.AddField(
            model_name="itemtype",
            name="system_name",
            field=models.CharField(
                blank=True,
                help_text="系统内部名称, e.g., 'sword'",
                max_length=50,
                null=True,
                unique=True,
            ),
        ),
        migrations.AddField(
            model_name="material",
            name="display_name",
            field=models.CharField(
                blank=True, help_text="用于显示的名称, e.g., '钻石'", max_length=50, null=True
            ),
        ),
        migrations.AddField(
            model_name="material",
            name="system_name",
            field=models.CharField(
                blank=True,
                help_text="系统内部名称, e.g., 'diamond'",
                max_length=50,
                null=True,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="baseitem",
            name="item_id",
            field=models.CharField(
                editable=False,
                help_text="自动生成的 Minecraft ID",
                max_length=100,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="baseitem",
            name="item_type",
            field=models.ForeignKey(
                blank=True,
                help_text="物品的基础类型",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="MC_command.itemtype",
            ),
        ),
        migrations.AlterField(
            model_name="baseitem",
            name="material",
            field=models.ForeignKey(
                blank=True,
                help_text="物品的材质",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="MC_command.material",
            ),
        ),
        migrations.AlterField(
            model_name="baseitem",
            name="name",
            field=models.CharField(
                editable=False, help_text="自动生成的显示名称", max_length=100
            ),
        ),
    ]
