# Generated by Django 5.2 on 2025-06-25 13:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("MC_command", "0015_alter_baseitem_options_alter_itemtype_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="generatedcommand",
            name="base_item",
        ),
        migrations.AddField(
            model_name="generatedcommand",
            name="item_type",
            field=models.ForeignKey(
                blank=True,
                help_text="物品的基础类型",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="MC_command.itemtype",
            ),
        ),
        migrations.AddField(
            model_name="generatedcommand",
            name="material",
            field=models.ForeignKey(
                blank=True,
                help_text="物品的材质",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="MC_command.material",
            ),
        ),
        migrations.AddField(
            model_name="itemtype",
            name="function_type",
            field=models.CharField(
                choices=[
                    ("all", "普通物品"),
                    ("spawn_egg", "生成蛋"),
                    ("potion", "药水(箭/食物)"),
                    ("written_book", "成书"),
                    ("firework", "烟花火箭"),
                ],
                default="all",
                help_text="物品的功能分类",
                max_length=50,
                verbose_name="功能类型",
            ),
        ),
        migrations.DeleteModel(
            name="BaseItem",
        ),
    ]
