# Generated by Django 5.2 on 2025-06-25 13:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("MC_command", "0016_remove_generatedcommand_base_item_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="itemtype",
            options={
                "ordering": ["display_name"],
                "verbose_name": "物品类型",
                "verbose_name_plural": "🗡物品类型",
            },
        ),
        migrations.AlterModelOptions(
            name="material",
            options={
                "ordering": ["display_name"],
                "verbose_name": "材质",
                "verbose_name_plural": "💎材质",
            },
        ),
    ]
