# Generated by Django 5.2 on 2025-06-25 13:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("MC_command", "0018_alter_attributetype_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="attributetype",
            options={
                "ordering": ["name"],
                "verbose_name": "属性效果",
                "verbose_name_plural": "[💪]属性效果",
            },
        ),
        migrations.AlterModelOptions(
            name="enchantment",
            options={
                "ordering": ["name"],
                "verbose_name": "附魔效果",
                "verbose_name_plural": "[🔥]附魔效果",
            },
        ),
        migrations.AlterModelOptions(
            name="generatedcommand",
            options={"verbose_name": "物品配置", "verbose_name_plural": "<0>完整物品配置"},
        ),
        migrations.AlterModelOptions(
            name="itemtype",
            options={
                "ordering": ["display_name"],
                "verbose_name": "物品类型",
                "verbose_name_plural": "<🗡>物品类型",
            },
        ),
        migrations.AlterModelOptions(
            name="material",
            options={
                "ordering": ["display_name"],
                "verbose_name": "材质",
                "verbose_name_plural": "<💎>材质",
            },
        ),
        migrations.AlterModelOptions(
            name="minecraftversion",
            options={
                "ordering": ["ordering_id"],
                "verbose_name": "版本",
                "verbose_name_plural": "<1>版本",
            },
        ),
        migrations.AlterModelOptions(
            name="potioneffecttype",
            options={
                "ordering": ["name"],
                "verbose_name": "药水效果",
                "verbose_name_plural": "[💧]药水效果",
            },
        ),
    ]
