# Generated by Django 5.2 on 2025-06-26 00:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("MC_command", "0019_alter_attributetype_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="enchantment",
            name="enchant_type",
            field=models.CharField(
                choices=[
                    ("weapon", "武器"),
                    ("tool", "工具"),
                    ("armor", "盔甲"),
                    ("fishing_rod", "钓鱼竿"),
                    ("trident", "三叉戟"),
                    ("bow", "弓"),
                    ("crossbow", "弩"),
                    ("all", "杂项"),
                    ("helmet", "头盔"),
                    ("boots", "靴子"),
                ],
                default="all",
                help_text="附魔类型, 例如 'weapon', 'armor', 'fishing_rod', 'trident' 等",
                max_length=50,
            ),
        ),
    ]
