# Generated by Django 5.2 on 2025-06-26 01:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("MC_command", "0020_alter_enchantment_enchant_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="AppliedFireworkExplosion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "shape",
                    models.CharField(
                        choices=[
                            (0, "小球型 (Small Ball)"),
                            (1, "大球型 (Large Ball)"),
                            (2, "星型 (Star-shaped)"),
                            (3, "苦力怕型 (Creeper-shaped)"),
                            (4, "爆裂型 (Burst)"),
                            ("random", "随机形状"),
                        ],
                        default=0,
                        max_length=10,
                        verbose_name="形状",
                    ),
                ),
                ("has_trail", models.BooleanField(default=False, verbose_name="有尾迹")),
                ("has_twinkle", models.BooleanField(default=False, verbose_name="闪烁")),
                (
                    "colors",
                    models.CharField(
                        default="[]",
                        help_text="JSON格式的颜色整数列表, 或 'random' 表示随机",
                        max_length=255,
                        verbose_name="主颜色",
                    ),
                ),
                (
                    "fade_colors",
                    models.CharField(
                        default="[]",
                        help_text="JSON格式的淡出颜色整数列表, 或 'random' 表示随机",
                        max_length=255,
                        verbose_name="淡出颜色",
                    ),
                ),
                (
                    "repeat_count",
                    models.PositiveIntegerField(
                        default=1, help_text="此烟火之星在烟花火箭中重复的次数", verbose_name="重复次数"
                    ),
                ),
                (
                    "command",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="firework_explosions",
                        to="MC_command.generatedcommand",
                    ),
                ),
            ],
            options={
                "verbose_name": "烟火爆炸效果",
                "verbose_name_plural": "烟火爆炸效果",
            },
        ),
    ]
