# Generated by Django 5.2 on 2025-06-26 03:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("MC_command", "0021_appliedfireworkexplosion"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appliedfireworkexplosion",
            name="colors",
            field=models.CharField(
                default="[]",
                help_text='JSON 格式的颜色值列表, e.g., [16711680, 16776960] for red, yellow. Use "random" for random colors.',
                max_length=200,
                verbose_name="颜色",
            ),
        ),
        migrations.AlterField(
            model_name="appliedfireworkexplosion",
            name="fade_colors",
            field=models.CharField(
                blank=True,
                default="[]",
                help_text='效果消失时渐变到的颜色 (JSON 列表或 "random")',
                max_length=200,
                verbose_name="淡出颜色",
            ),
        ),
        migrations.AlterField(
            model_name="appliedfireworkexplosion",
            name="has_trail",
            field=models.BooleanField(default=False, verbose_name="有拖尾效果"),
        ),
        migrations.AlterField(
            model_name="appliedfireworkexplosion",
            name="has_twinkle",
            field=models.BooleanField(default=False, verbose_name="有闪烁效果"),
        ),
        migrations.AlterField(
            model_name="appliedfireworkexplosion",
            name="repeat_count",
            field=models.PositiveSmallIntegerField(
                default=1, help_text="此爆炸效果重复多少次", verbose_name="重复次数"
            ),
        ),
        migrations.AlterField(
            model_name="appliedfireworkexplosion",
            name="shape",
            field=models.CharField(
                choices=[
                    ("0", "小球型"),
                    ("1", "大球型"),
                    ("2", "星型"),
                    ("3", "苦力怕脸型"),
                    ("4", "爆裂型"),
                    ("random", "随机形状"),
                ],
                default="0",
                max_length=10,
                verbose_name="爆炸形状",
            ),
        ),
    ]
