# Generated by Django 5.2 on 2025-06-26 11:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("MC_command", "0022_alter_appliedfireworkexplosion_colors_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="BooleanComponentType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="组件名称")),
                ("key_new", models.CharField(max_length=100, verbose_name="新版本键名")),
                (
                    "key_old",
                    models.CharField(blank=True, max_length=100, verbose_name="旧版本键名"),
                ),
                (
                    "syntax_new",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="新版本用法说明"
                    ),
                ),
                (
                    "syntax_old",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="旧版本用法说明"
                    ),
                ),
                (
                    "max_version",
                    models.ForeignKey(
                        blank=True,
                        help_text="该项目有效的最高版本 (留空表示无限制)",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="MC_command.minecraftversion",
                    ),
                ),
                (
                    "min_version",
                    models.ForeignKey(
                        blank=True,
                        help_text="该项目有效的最低版本 (留空表示无限制)",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="MC_command.minecraftversion",
                    ),
                ),
            ],
            options={
                "verbose_name": "布尔型组件定义",
                "verbose_name_plural": "[🔨]布尔型组件定义",
            },
        ),
        migrations.CreateModel(
            name="AppliedBooleanComponent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value", models.BooleanField(default=True, verbose_name="启用？")),
                (
                    "command",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="boolean_components",
                        to="MC_command.generatedcommand",
                    ),
                ),
                (
                    "component",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="MC_command.booleancomponenttype",
                    ),
                ),
            ],
            options={
                "verbose_name": "布尔型组件",
                "verbose_name_plural": "布尔型组件",
                "unique_together": {("command", "component")},
            },
        ),
    ]
