# Generated by Django 5.2 on 2025-06-26 12:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("MC_command", "0023_booleancomponenttype_appliedbooleancomponent"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="booleancomponenttype",
            options={"verbose_name": "布尔型组件定义", "verbose_name_plural": "[⚙]布尔型组件定义"},
        ),
        migrations.RemoveField(
            model_name="booleancomponenttype",
            name="key_new",
        ),
        migrations.RemoveField(
            model_name="booleancomponenttype",
            name="key_old",
        ),
        migrations.RemoveField(
            model_name="booleancomponenttype",
            name="syntax_new",
        ),
        migrations.RemoveField(
            model_name="booleancomponenttype",
            name="syntax_old",
        ),
        migrations.AddField(
            model_name="booleancomponenttype",
            name="description",
            field=models.CharField(blank=True, max_length=200, verbose_name="说明"),
        ),
        migrations.AddField(
            model_name="booleancomponenttype",
            name="false_str",
            field=models.CharField(default="", max_length=100, verbose_name="关闭时字符串"),
        ),
        migrations.AddField(
            model_name="booleancomponenttype",
            name="true_str",
            field=models.CharField(default="", max_length=100, verbose_name="启用时字符串"),
        ),
        migrations.AlterField(
            model_name="booleancomponenttype",
            name="name",
            field=models.CharField(max_length=100, verbose_name="名称"),
        ),
    ]
