# Generated by Django 5.2 on 2025-06-26 14:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("MC_command", "0024_alter_booleancomponenttype_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booleancomponenttype",
            name="false_str",
            field=models.CharField(
                blank=True, default="", max_length=100, verbose_name="关闭时字符串"
            ),
        ),
    ]
