# Generated by Django 5.2 on 2025-09-11 07:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("MC_command", "0026_alter_enchantment_enchant_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="enchantment",
            name="enchant_type",
            field=models.CharField(
                choices=[
                    ("weapon", "武器"),
                    ("tool", "工具"),
                    ("armor", "盔甲"),
                    ("chestplate", "胸甲"),
                    ("leggings", "护腿"),
                    ("boots", "靴子"),
                    ("fishing_rod", "钓鱼竿"),
                    ("trident", "三叉戟"),
                    ("bow", "弓"),
                    ("crossbow", "弩"),
                    ("all", "所有物品"),
                    ("helmet", "头盔"),
                    ("wand", "[铁魔法]法杖"),
                    ("magic_books", "[铁魔法]法术书"),
                    ("unknown", "未知"),
                ],
                default="all",
                help_text="附魔类型, 例如 'weapon', 'armor', 'fishing_rod', 'trident' 等",
                max_length=50,
            ),
        ),
    ]
