# Generated by Django 5.2 on 2025-09-11 10:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("MC_command", "0027_alter_enchantment_enchant_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="Spell",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "spell_id",
                    models.CharField(
                        help_text="法术的唯一ID, 例如 'cataclysm_spellbooks:summon_koboleton'",
                        max_length=150,
                        unique=True,
                    ),
                ),
                (
                    "name",
                    models.CharField(help_text="法术的显示名称, 例如 '召唤骷髅兵'", max_length=100),
                ),
                (
                    "max_version",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="MC_command.minecraftversion",
                        verbose_name="最高兼容版本",
                    ),
                ),
                (
                    "min_version",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="MC_command.minecraftversion",
                        verbose_name="最低兼容版本",
                    ),
                ),
            ],
            options={
                "verbose_name": "法术",
                "verbose_name_plural": "[🪄]法术",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="SpellInfusion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "spell_wheel",
                    models.BooleanField(
                        default=True, verbose_name="启用法术轮盘 (spellWheel)"
                    ),
                ),
                (
                    "must_equip",
                    models.BooleanField(
                        default=False, verbose_name="必须装备才能施法 (mustEquip)"
                    ),
                ),
                (
                    "max_spells",
                    models.PositiveSmallIntegerField(
                        default=1, verbose_name="最大法术数量 (maxSpells)"
                    ),
                ),
                (
                    "command",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="spell_infusion",
                        to="MC_command.generatedcommand",
                    ),
                ),
            ],
            options={
                "verbose_name": "法术注入配置",
                "verbose_name_plural": "法术注入配置",
            },
        ),
        migrations.CreateModel(
            name="AppliedSpell",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "level",
                    models.PositiveIntegerField(default=1, verbose_name="法术等级 (level)"),
                ),
                (
                    "index",
                    models.PositiveSmallIntegerField(
                        default=0,
                        help_text="法术在列表中的位置，从0开始",
                        verbose_name="法术索引 (index)",
                    ),
                ),
                (
                    "locked",
                    models.BooleanField(default=False, verbose_name="是否锁定 (locked)"),
                ),
                (
                    "spell",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="MC_command.spell",
                        verbose_name="选择的法术",
                    ),
                ),
                (
                    "infusion_config",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="spells",
                        to="MC_command.spellinfusion",
                        verbose_name="所属法术配置",
                    ),
                ),
            ],
            options={
                "verbose_name": "应用的法术",
                "verbose_name_plural": "应用的法术",
                "ordering": ["index"],
                "unique_together": {("infusion_config", "index")},
            },
        ),
    ]
