# Generated by Django 5.2 on 2025-09-30 07:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("MC_command", "0028_spell_spellinfusion_appliedspell"),
        ("contenttypes", "0002_remove_content_type_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EntityTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="例如 'undead', 'merchant', 'mob'",
                        max_length=50,
                        unique=True,
                    ),
                ),
                ("description", models.CharField(blank=True, max_length=200)),
            ],
            options={
                "verbose_name": "实体标签",
                "verbose_name_plural": "[🏷️]实体标签",
            },
        ),
        migrations.AlterModelOptions(
            name="appliedpotioneffect",
            options={"verbose_name": "应用的效果", "verbose_name_plural": "应用的效果 (药水/属性)"},
        ),
        migrations.AddField(
            model_name="appliedattribute",
            name="content_type",
            field=models.ForeignKey(
                blank=True,
                help_text="关联对象的类型 (物品或实体)",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="contenttypes.contenttype",
            ),
        ),
        migrations.AddField(
            model_name="appliedattribute",
            name="object_id",
            field=models.PositiveIntegerField(
                blank=True, help_text="关联对象的ID", null=True
            ),
        ),
        migrations.AddField(
            model_name="appliedpotioneffect",
            name="content_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="contenttypes.contenttype",
            ),
        ),
        migrations.AddField(
            model_name="appliedpotioneffect",
            name="object_id",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="appliedattribute",
            name="command",
            field=models.ForeignKey(
                blank=True,
                help_text="[旧] 直接关联到物品配置",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attributes",
                to="MC_command.generatedcommand",
            ),
        ),
        migrations.AlterField(
            model_name="appliedpotioneffect",
            name="command",
            field=models.ForeignKey(
                blank=True,
                help_text="[旧] 直接关联到物品配置",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="potion_effects",
                to="MC_command.generatedcommand",
                verbose_name="所属命令",
            ),
        ),
        migrations.CreateModel(
            name="EntityEquipmentSlot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "slot",
                    models.CharField(
                        choices=[
                            ("mainhand", "主手"),
                            ("offhand", "副手"),
                            ("head", "头部"),
                            ("chest", "胸部"),
                            ("legs", "腿部"),
                            ("feet", "脚部"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "drop_chance",
                    models.FloatField(default=1.0, help_text="物品的掉落几率 (0.0 到 1.0)"),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="MC_command.generatedcommand",
                    ),
                ),
            ],
            options={
                "verbose_name": "实体装备槽",
                "verbose_name_plural": "实体装备槽",
            },
        ),
        migrations.CreateModel(
            name="EntityComponentType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(help_text="显示名称, e.g., '禁用AI'", max_length=100),
                ),
                (
                    "nbt_key",
                    models.CharField(help_text="NBT键, e.g., 'NoAI'", max_length=100),
                ),
                (
                    "value_type",
                    models.CharField(
                        choices=[
                            ("boolean", "布尔值 (是/否)"),
                            ("integer", "整数"),
                            ("float", "浮点数"),
                            ("string", "字符串"),
                            ("position_vector", "坐标向量 [x, y, z]"),
                            ("json", "自定义JSON文本"),
                        ],
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True, help_text="为用户解释这个组件的作用")),
                (
                    "tags",
                    models.ManyToManyField(
                        blank=True,
                        help_text="将此组件限制在拥有特定标签的实体上",
                        to="MC_command.entitytag",
                    ),
                ),
            ],
            options={
                "verbose_name": "实体组件定义",
                "verbose_name_plural": "[⚙️]实体组件定义",
            },
        ),
        migrations.CreateModel(
            name="EntityType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "entity_id",
                    models.CharField(
                        help_text="例如 'minecraft:zombie'", max_length=100, unique=True
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("tags", models.ManyToManyField(blank=True, to="MC_command.entitytag")),
            ],
            options={
                "verbose_name": "实体种类",
                "verbose_name_plural": "[🐑]实体种类",
            },
        ),
        migrations.CreateModel(
            name="GeneratedEntity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(help_text="为这个实体配置起一个名字", max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "entity_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="MC_command.entitytype",
                    ),
                ),
                (
                    "equipment",
                    models.ManyToManyField(
                        blank=True,
                        related_name="equipped_by_entities",
                        through="MC_command.EntityEquipmentSlot",
                        to="MC_command.generatedcommand",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entities",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "实体配置",
                "verbose_name_plural": "<Σ>完整实体配置",
            },
        ),
        migrations.AddField(
            model_name="entityequipmentslot",
            name="entity",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="MC_command.generatedentity",
            ),
        ),
        migrations.CreateModel(
            name="TradeRecipe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "max_uses",
                    models.PositiveIntegerField(default=10, help_text="最大交易次数"),
                ),
                ("xp", models.PositiveIntegerField(default=1, help_text="给予玩家的经验值")),
                ("price_multiplier", models.FloatField(default=0.0)),
                (
                    "buy_item1",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="MC_command.generatedcommand",
                    ),
                ),
                (
                    "buy_item2",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="MC_command.generatedcommand",
                    ),
                ),
                (
                    "sell_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="MC_command.generatedcommand",
                    ),
                ),
                (
                    "trader",
                    models.ForeignKey(
                        limit_choices_to={"entity_type__tags__name__in": ["merchant"]},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trades",
                        to="MC_command.generatedentity",
                    ),
                ),
            ],
            options={
                "verbose_name": "村民交易",
                "verbose_name_plural": "村民交易",
                "ordering": ["id"],
            },
        ),
        migrations.AlterUniqueTogether(
            name="entityequipmentslot",
            unique_together={("entity", "slot")},
        ),
        migrations.CreateModel(
            name="AppliedEntityComponent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value", models.CharField(max_length=500)),
                (
                    "component_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="MC_command.entitycomponenttype",
                    ),
                ),
                (
                    "entity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="components",
                        to="MC_command.generatedentity",
                    ),
                ),
            ],
            options={
                "verbose_name": "应用的实体组件",
                "verbose_name_plural": "应用的实体组件",
                "unique_together": {("entity", "component_type")},
            },
        ),
    ]
