# Generated by Django 5.2 on 2025-10-01 12:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("MC_command", "0029_entitytag_alter_appliedpotioneffect_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="generatedentity",
            name="passengers",
            field=models.ManyToManyField(
                blank=True,
                related_name="ridden_by",
                to="MC_command.generatedentity",
                verbose_name="乘客实体",
            ),
        ),
        migrations.AddField(
            model_name="generatedentity",
            name="source_item",
            field=models.ForeignKey(
                blank=True,
                help_text="关联的物品配置 (用于'物品实体'的Item标签, 或'投射物'的TridentItem等标签)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="used_by_entities",
                to="MC_command.generatedcommand",
                verbose_name="来源物品",
            ),
        ),
        migrations.CreateModel(
            name="AreaEffectCloudProperties",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "duration",
                    models.IntegerField(default=600, help_text="效果云的总持续时间 (ticks)"),
                ),
                (
                    "wait_time",
                    models.IntegerField(
                        default=20, help_text="效果云生成后，开始施加效果前的等待时间 (ticks)"
                    ),
                ),
                (
                    "reapplication_delay",
                    models.IntegerField(
                        default=40, help_text="对同一个实体重复施加效果的间隔时间 (ticks)"
                    ),
                ),
                (
                    "duration_on_use",
                    models.IntegerField(
                        default=0, help_text="每次有实体受影响时，总持续时间减少的量 (ticks)"
                    ),
                ),
                ("radius", models.FloatField(default=3.0, help_text="效果云的初始半径（米）")),
                (
                    "radius_on_use",
                    models.FloatField(
                        default=-0.5, help_text="每次有实体受影响时，半径变化的量（可以为负数）"
                    ),
                ),
                (
                    "radius_per_tick",
                    models.FloatField(
                        default=-0.005, help_text="每 tick 半径变化的量（可以为负数，实现缩小）"
                    ),
                ),
                (
                    "particle_type",
                    models.CharField(
                        default="minecraft:effect",
                        help_text="粒子效果的ID, 例如 'minecraft:entity_effect' 或 'minecraft:flame'",
                        max_length=100,
                    ),
                ),
                (
                    "entity",
                    models.OneToOneField(
                        limit_choices_to={
                            "entity_type__entity_id": "minecraft:area_effect_cloud"
                        },
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="aec_properties",
                        to="MC_command.generatedentity",
                        verbose_name="所属实体配置",
                    ),
                ),
            ],
            options={
                "verbose_name": "粒子效果云属性",
                "verbose_name_plural": "粒子效果云属性",
            },
        ),
    ]
