# Generated by Django 5.2 on 2025-10-01 13:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("MC_command", "0030_generatedentity_passengers_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="areaeffectcloudproperties",
            name="particle_type",
        ),
        migrations.CreateModel(
            name="ParticleType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "particle_id",
                    models.CharField(
                        help_text="粒子的ID, 例如 'minecraft:flame'",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "name",
                    models.CharField(help_text="用于显示的名称, 例如 '火焰'", max_length=100),
                ),
                (
                    "max_version",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="MC_command.minecraftversion",
                    ),
                ),
                (
                    "min_version",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="MC_command.minecraftversion",
                    ),
                ),
            ],
            options={
                "verbose_name": "粒子效果类型",
                "verbose_name_plural": "[✨]粒子效果类型",
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="areaeffectcloudproperties",
            name="particle",
            field=models.ForeignKey(
                blank=True,
                help_text="选择效果云要显示的粒子效果",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="MC_command.particletype",
            ),
        ),
    ]
