# Generated by Django 5.2 on 2025-10-05 05:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("MC_command", "0031_remove_areaeffectcloudproperties_particle_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="traderecipe",
            name="buy_item1_count",
            field=models.PositiveIntegerField(
                blank=True, help_text="留空则使用所选物品配置的默认数量", null=True
            ),
        ),
        migrations.AddField(
            model_name="traderecipe",
            name="buy_item2_count",
            field=models.PositiveIntegerField(
                blank=True, help_text="留空则使用所选物品配置的默认数量", null=True
            ),
        ),
        migrations.AddField(
            model_name="traderecipe",
            name="sell_item_count",
            field=models.PositiveIntegerField(
                blank=True, help_text="留空则使用所选物品配置的默认数量", null=True
            ),
        ),
        migrations.AlterField(
            model_name="appliedentitycomponent",
            name="value",
            field=models.CharField(max_length=5000),
        ),
    ]
