# Generated by Django 5.2 on 2025-11-21 15:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("MC_command", "0032_traderecipe_buy_item1_count_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserWallet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "balance",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=20,
                        verbose_name="当前金币余额",
                    ),
                ),
                (
                    "total_recharged",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=20,
                        verbose_name="历史累计充值(RMB)",
                    ),
                ),
                (
                    "total_earnings",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=20,
                        verbose_name="历史游戏盈利总额",
                    ),
                ),
                (
                    "black_curtain_rate",
                    models.FloatField(
                        default=1.0,
                        help_text="运气修正值。1.0=正常，0.5=霉运(胜率减半)，2.0=欧皇(胜率翻倍)。用于后台控制该玩家输赢。",
                    ),
                ),
                (
                    "is_flagged",
                    models.BooleanField(
                        default=False, help_text="标记为问题赌狗，后台特殊显示", verbose_name="重点监控"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wallet",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "用户钱包(黑幕配置)",
                "verbose_name_plural": "💰用户钱包(黑幕配置)",
            },
        ),
        migrations.CreateModel(
            name="GameTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=20, verbose_name="变动金额"
                    ),
                ),
                (
                    "trans_type",
                    models.CharField(
                        choices=[
                            ("recharge", "后台充值(增加VIP)"),
                            ("admin_grant", "系统赠送(不加VIP)"),
                            ("game_bet", "游戏下注"),
                            ("game_win", "游戏派彩"),
                            ("withdraw", "提现/扣除"),
                        ],
                        default="game_bet",
                        max_length=20,
                        verbose_name="交易类型",
                    ),
                ),
                (
                    "description",
                    models.CharField(blank=True, max_length=255, verbose_name="备注/游戏名"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "wallet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to="MC_command.userwallet",
                    ),
                ),
            ],
            options={
                "verbose_name": "资金流水",
                "verbose_name_plural": "🧾资金流水",
            },
        ),
    ]
